apiVersion: v1
kind: LimitRange
metadata:
  name: min-max
spec:
  limits:
  - type: Container
    max:
      memory: "250Mi"
      cpu: "500m"
    min:
      cpu: "200m"
      memory: "150Mi"        

