apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busyhttp
  name: busyhttp
spec:
  containers:
  - image: otomato/busyhttp
    name: busyhttp
    resources:
      limits:
        memory: 20Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
