apiVersion: v1
kind: ResourceQuota
metadata:
  name: low-priority-quota
spec:
  hard:
    cpu: "1000"
    memory: 1Gi
    pods: "10"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["low-priority"]